### ISSUE TITLE
Update reminder cron job runs at GMT and not IST.

### ISSUE THREAD

**Issue by pri1311** [CommunityOfCoders/Inheritance-Bot#3]
The following message should be sent at 12PM IST.
However, cron job is currently running on GMT.
<img width="679" alt="Screenshot 2022-10-23 at 6 50 14 PM" src="https://user-images.githubusercontent.com/64613009/197394609-88d1ea85-57ab-4591-88d7-8f8f178e88b4.png">

The issue can be solved either by changing the time specified in the cron job command or by mentioning the timezone. Latter seems to be a better option.
Reference to adding timezone to cronjob - [Cron methods
](https://www.npmjs.com/package/node-cron?id=user-content-cron-methods#:~:text=%7D\)%3B-,Cron%20methods,-Schedule)

**Comment by TuhinChatterjee02** [comment]
var cron = require('node-cron');

 cron.schedule('0 12 * * 7', () => {
   console.log('Update time @mentee! Provide your weekly updates to your respective mentors');
 }, {
   scheduled: true,
   timezone: "Asia/Kolkata"
 });

**Comment by unmani-shinde** [comment]
var cron = require('node-cron');

 cron.schedule('0 1 * * *', () => {
   console.log('Update time @mentee! Provide your weekly updates to your respective mentors'');
 }, {
   scheduled: true,
   timezone: "Asia/Kolkata"
 });

**Comment by Shaun-Codes** [comment]
> var cron = require('node-cron');
> 
>  cron.schedule('* * 12 * *', () => {
>    console.log('Update time @mentee! Provide your weekly updates to your respective mentors');
>  }, {
>    scheduled: true,
>    timezone: "Asia/Kolkata"
>  });

**Comment by Shaun-Codes** [comment]
> var cron = require('node-cron');
> 
>  cron.schedule('* * 12 * *', () => {
>    console.log('Update time @mentee! Provide your weekly updates to your respective mentors');
>  }, {
>    scheduled: true,
>    timezone: "Asia/Kolkata"
>  });

**Comment by KedarDhamankar** [comment]
cron.schedule('00 12 * * 7', function () {
  // remind mentees to update their mentors on 12pm of every Sunday
  const channel = client.channels.cache.get(
    process.env.CHANNEL_ID_ANNOUNCEMENTS
  );
  channel.send(
    `Update time <@&${process.env.ROLE_ID_MENTEES}>! Provide your weekly updates to your respective mentors.`
  );
}, {
  scheduled: true,
  timezone: "Asia/Kolkata"
});

**Comment by Shaun-Codes** [comment]
> var cron = require('node-cron');
> 
>  cron.schedule('* * 12 * *', () => {
>    console.log('Update time @mentee! Provide your weekly updates to your respective mentors');
>  }, {
>    scheduled: true,
>    timezone: "Asia/Kolkata"
>  });

**Comment by KedarDhamankar** [comment]
A silly doubt
Do we have to comment the changes here first or do we have to directly send a PR?

**Comment by pri1311** [comment]
@KedarDhamankar nope, you don't have to comment here.
Checking your PR. Thanks!
